services:
    mongodb:
	image: mongo:latest
        container_name: mongodbcontainer
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: nduran06
            MONGO_INITDB_ROOT_PASSWORD: aygopass123
            MONGO_INITDB_DATABASE: aygoDB
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

